### ISSUE TITLE
Search for files in path different than the linked relative path (prepend string to path)

### ISSUE THREAD

**Issue by hghristov** [demsking/gulp-html-dependencies#3]
Hello. 

I'm using PHP and I've put parts of my project into a `partials/` folder, and I'm getting the following error:

> Error: ENOENT: no such file or directory, open '[..]project\src\bower_components\jquery\dist\jquery.js'

My relevant project structure is as follows:

```
project/
├── bower_components
├── dist
├── node_modules
├── src
│   ├── index.php
│   └──  partials
│       ├── header.php
│       └── footer.php
```

The link to jquery in my footer partial is as follows:
`<script src="../bower_components/jquery/dist/jquery.js"></script>`

The problem is since I'm using PHP and including my partial in my index file that's located in `project/src/` I need to make the url link only one level up like this `../bower_components` instead of two levels `../../bower_components`. 

gulp-html-dependencies is looking for `bower_components` in my `src/` folder which is why I'm getting the error, but I need it to search one more level up.

Is there a way to do this? Perhaps an option to prepend a `../` string to each file before handling it?

**Comment by demsking** [comment]
This repo is deprecated. Please use [gulp-web-dependencies](https://github.com/demsking/gulp-web-dependencies) instead.

The `gulp-web-dependencies` plugin have a `folders` option to help you to define your own search folder pattern. Please read the [documentation](https://github.com/demsking/gulp-web-dependencies#use-the-your-own-search-folders-pattern) for the usage.
